---
- name: Install python-apt
  apt:
    name: python-apt
    state: present

- name: Install Apache2
  apt:
    name: apache2
    state: present

- name: copy index
  ansible.builtin.copy:
    src: /home/diorburchfiel/adburchfie42-csc2510-infrastructure/files/site/index.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: copy config
  ansible.builtin.copy:
  src: /home/diorburchfiel/adburchfie42-csc2510-infrastructure/files/config/apache2.config
  dest: /etc/apache2/apache2.conf
  owner: root
  group: root
  mode: 0644

- name: create symlink
  ansible.builtin.file:
    src: /etc/apache2/mods-available/headers.load
    dest: /etc/apache2/mods-enabled/headers.load
    state: link

