---
- hosts: all 
  become: yes  
  tasks:
    - name: Update APT
      ansible.builtin.apt:
        update_cache: yes 

   - name: Install python-apt package
     ansible.builtin.apt:
        name: python-apt
        state: present  # Ensure the package is present

    - name: Install apache2 package
      ansible.builtin.apt:
        name: apache2
        state: present  # Ensure the package is present
    - name: copy index 
      ansible.builtin.copy:
        src: /home/diorburchfiel/adburchfie42-csc2510-infrastructure/files/site 
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
    - name: copy config
      ansible.builtin.copy:
        src: /home/diorburchfiel/adburchfie42-csc2510-infrastructure/files/config
        dest: /etc/apache2/apache2.conf
        owner: root
        group: root
        mode: 0644
    - name: create symlink 
      ansible.builtin.file: 
        src: /etc/apache2/mods-available/headers.load
        dest: /etc/apache2/mods-enabled/headers.load
        state: link
    - name: restart apache2
      ansible.builtin.service:
        name: apache2
        state: restarted
